version: "3.9"
services:
  redis:
    container_name: cenomod_redis
    image: redis

    command: redis-server --requirepass C0KHfa7sa9AmzNpWzcAu9eC67Reip7R5M

    ports:
      - 6379:6379
    networks:
      - backend

  node-server:
    container_name: cenomod_backed
    build: .
    depends_on: [ redis ]
    ports:
      - 8080:8080
    volumes:
      - ./data:/usr/src/app/data
      - ./log:/usr/src/app/log
    networks:
      - backend

networks:
  backend:
    driver: bridge