version: "3.9"
services:
  redis:
    image: redis

    command: redis-server --requirepass C0KHfa7sa9AmzNpWzcAu9eC67Reip7R5M

    ports:
      - 6379:6379
    networks:
      node_net:
        ipv4_address: 192.168.1.3

  node-server:
    build: .
    ports:
      - 8081:8080
    volumes:
      - ./data:/usr/src/app/data
      - ./log:/usr/src/app/log
    networks:
      node_net:
        ipv4_address: 192.168.1.2

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24